models:
  - name: "LLaVA-1.5-7B"
    model_id: "llava-hf/llava-1.5-7b-hf"
    type: "llava"
  - name: "Qwen2-VL-7B"
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
    type: "qwen-vl"
  - name: "DVIT-LLaVA-7B"
    model_id: "llava-hf/llava-1.5-7b-hf"
    type: "dvit_llava"
  - name: "LLaVA-1.5-7B-CoT-LoRA"
    model_id: "llava-hf/llava-1.5-7b-hf"
    type: "llava-lora"
    adapter_path: "./llava-1.5-7b-vqa-cot-lora" 
  - name: "Qwen2-VL-7B-CoT-LoRA"
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
    type: "qwen-lora"
    adapter_path: "./qwen-vl-7b-vqa-cot-lora"
  - name: "LLaVA-1.5-7B (ScienceQA-LoRA)"
    model_id: "llava-hf/llava-1.5-7b-hf"
    type: "llava-lora"
    adapter_path: "./llava-1.5-7b-scienceqa-lora"
  - name: "Qwen2-VL-7B (ScienceQA-LoRA)"
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
    type: "qwen-lora"
    adapter_path: "./qwen-vl-7b-scienceqa-lora"
  - name: "LLaVA-1.5-7B (POPE-LoRA)"
    model_id: "llava-hf/llava-1.5-7b-hf"
    type: "llava-lora"
    adapter_path: "./llava-1.5-7b-pope-cot-lora"
  - name: "Qwen2-VL-7B (POPE-LoRA)"
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
    type: "qwen-lora"
    adapter_path: "./qwen-vl-7b-pope-cot-lora"
  - name: "LLaVA-NeXT-7B"
    model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
    type: "llava-next"
  - name: "InstructBLIP"
    model_id: "Salesforce/instructblip-vicuna-7b" 
    type: "instructblip"
  - name: "LLaVA-1.5-13B"
    model_id: "llava-hf/llava-1.5-13b-hf"
    type: "llava"
  - name: "Qwen3-VL-8B-Instruct"
    model_id: "Qwen/Qwen3-VL-8B-Instruct"
    type: "qwen3-vl"
  - name: "Gemma-3-12B-IT"
    model_id: "google/gemma-3-12b-it"
    type: "gemma3"
  - name: "Hybrid-LLaVA-RefCOCOg"
    model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
    type: "structural_llava"
    custom_modules_path: "./final_adapter_refcocog/custom_modules.bin"
    adapter_path: "./final_adapter_refcocog/llava_projector_lora"