dataset_id: "LightChen2333/M3CoT"

num_val_samples: 1000

max_new_tokens: 200
device: "cuda"
batch_size: 8

models:
  - name: "LLaVA-NeXT-7B"
    model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
    type: "llava-next"
