dataset_id: "derek-thomas/ScienceQA"

num_train_samples: 2000
num_val_samples: 1000

learning_rate: 1e-4
epochs: 1
save_steps: 100

model_output_dir_llava: "llava-1.5-7b-scienceqa-lora"
model_output_dir_qwen: "qwen-vl-7b-scienceqa-lora"

initial_lora_path_llava: "./llava-1.5-7b-vqa-cot-lora" 
initial_lora_path_qwen: "./qwen-vl-7b-vqa-cot-lora"

max_new_tokens: 200
device: "cuda"
batch_size: 6

models:
  - name: "Hybrid-LLaVA-RefCOCOg"
    model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
    type: "structural_llava"
    custom_modules_path: "./final_adapter/custom_modules.bin"
    adapter_path: "./final_adapter/llava_projector_lora"