dataset_id: "derek-thomas/ScienceQA"
max_new_tokens: 200
device: "cuda"
batch_size: 2

models:
  - name: "Hybrid-LLaVA-RefCOCOg"
    model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
    type: "structural_llava"
    custom_modules_path: "./final_adapter_llava_instruct1/custom_modules.bin"
    adapter_path: "./final_adapter_llava_instruct1/llava_projector_lora"
